#delimit ;

* Codes taken from the 2015 Geographic Cover. Several changes in gtcbsa and gtcsa

label values gereg    gereg;  
label define gereg   
	1           "NORTHEAST"                               
	2           "MIDWEST (FORMERLY NORTH CENTRAL)"        
	3           "SOUTH"                                   
	4           "WEST"                                    
;
label values gediv    gediv;  
label define gediv   
	1           "NEW ENGLAND"                             
	2           "MIDDLE ATLANTIC"                         
	3           "EAST NORTH CENTRAL"                      
	4           "WEST NORTH CENTRAL"                      
	5           "SOUTH ATLANTIC"                          
	6           "EAST SOUTH CENTRAL"                      
	7           "WEST SOUTH CENTRAL"                      
	8           "MOUNTAIN"                                
	9           "PACIFIC"                                 
;
label values gestfips gestfips;
label define gestfips
	1           "AL"                                      
	2           "AK"                                      
	4           "AZ"                                      
	5           "AR"                                      
	6           "CA"                                      
	8           "CO"                                      
	9           "CT"                                      
	10          "DE"                                      
	11          "DC"                                      
	12          "FL"                                      
	13          "GA"                                      
	15          "HI"                                      
	16          "ID"                                      
	17          "IL"                                      
	18          "IN"                                      
	19          "IA"                                      
	20          "KS"                                      
	21          "KY"                                      
	22          "LA"                                      
	23          "ME"                                      
	24          "MD"                                      
	25          "MA"                                      
	26          "MI"                                      
	27          "MN"                                      
	28          "MS"                                      
	29          "MO"                                      
	30          "MT"                                      
	31          "NE"                                      
	32          "NV"                                      
	33          "NH"                                      
	34          "NJ"                                      
	35          "NM"                                      
	36          "NY"                                      
	37          "NC"                                      
	38          "ND"                                      
	39          "OH"                                      
	40          "OK"                                      
	41          "OR"                                      
	42          "PA"                                      
	44          "RI"                                      
	45          "SC"                                      
	46          "SD"                                      
	47          "TN"                                      
	48          "TX"                                      
	49          "UT"                                      
	50          "VT"                                      
	51          "VA"                                      
	53          "WA"                                      
	54          "WV"                                      
	55          "WI"                                      
	56          "WY"                                      
;
destring gtcbsa, replace;
label values gtcbsa   gtcbsa; 
label define gtcbsa  
10180 "Abilene, TX "
10420 "Akron, OH "
10580 "Albany-Schenectady-Troy, NY "
10740 "Albuquerque, NM "
10900 "Allentown-Bethlehem-Easton, PA-NJ"
11100 "Amarillo, TX "
11460 "Ann Arbor, MI"
11540 "Appleton, WI"
11700 "Asheville, NC "
12020 "Athens-Clarke County, GA "
12060 "Atlanta-Sandy Springs-Roswell, GA "
12100 "Atlantic City-Hammonton, NJ"
12220 "Auburn-Opelika, AL"
12260 "Augusta-Richmond County, GA-SC"
12420 "Austin-Round Rock, TX"
12540 "Bakersfield, CA"
12580 "Baltimore-Columbia-Towson, MD"
12620 "Bangor, ME"
12700 "Barnstable, MA"
12940 "Baton Rouge, LA"
12980 "Battle Creek, MI"
13140 "Beaumont-Port Arthur, TX"
13460 "Bend-Redmond, OR"
13740 "Billings, MT "
13780 "Binghamton, NY"
13820 "Birmingham-Hoover, AL"
13980 "Blacksburg—Christiansburg-Radford, VA"
14010 "Bloomington, IL"
14020 "Bloomington, IN "
14260 "Boise City, ID"
14460 "Boston-Cambridge-Newton, MA-NH"
14500 "Boulder, CO"
14540 "Bowling Green, KY"
14860 "Bridgeport-Stamford-Norwalk, CT"
15180 "Brownsville-Harlingen, TX"
15380 "Buffalo-Cheektowaga-Niagara Falls, NY"
15500 "Burlington, NC"
15540 "Burlington-South Burlington, VT"
15680 "California-Lexington Park, MD "
15940 "  Canton-Massillon, OH"
15980 "  Cape Coral-Fort Myers, FL"
16060 "Carbondale-Marion, IL"
16300 "Cedar Rapids, IA "
16540 "Chambersburg-Waynesboro, PA"
16580 "Champaign-Urbana, IL"
16620 "Charleston, WV "
16700 "Charleston-North Charleston, SC"
16740 "Charlotte-Concord-Gastonia, NC-SC "
16820 "Charlottesville, VA"
16860 "Chattanooga, TN-GA "
16980 "Chicago-Naperville-Elgin, IL-IN-WI "
17020 "Chico, CA"
17140 "Cincinnati, OH-KY-IN"
17300 "Clarksville, TN-KY"
17420 "Cleveland, TN"
17460 "Cleveland-Elyria, OH"
17660 "Coeur d’Alene, ID"
17780 "College Station-Bryan, TX"
17820 "Colorado Springs, CO"
17900 "Columbia, SC"
17980 "Columbus, GA-AL"
18140 "Columbus, OH "
18580 "Corpus Christi, TX"
19100 "Dallas-Fort Worth-Arlington, TX "
19300 "Daphne-Fairhope-Foley, AL"
19340 "Davenport-Moline-Rock Island, IA-IL"
19380 "Dayton, OH"
19660 "Deltona-Daytona Beach-Ormond Beach, FL"
19740 "Denver-Aurora-Lakewood, CO"
19780 "Des Moines-West Des Moines, IA"
19820 "Detroit-Warren-Dearborn, MI"
20100 "Dover, DE"
20500 "Durham-Chapel Hill, NC"
20700 "East Stroudsburg, PA"
21140 "Elkhart-Goshen, IN"
21340 "El Paso, TX"
21500 "Erie, PA"
21660 "Eugene, OR"
21780 "Evansville, IN-KY  \n22020   Fargo, ND-MN "
22140 "Farmington, NM"
22180 "Fayetteville, NC"
22220 "Fayetteville-Springdale-Rogers, AR-MO"
22420 "Flint, MI "
22500 "Florence, SC"
22520 "Florence-Muscle Shoals, AL"
22660 "Fort Collins, CO"
22900 "Fort Smith, AR-OK "
23060 "Fort Wayne, IN"
23420 "Fresno, CA"
23540 "Gainesville, FL"
23580 "Gainesville, GA"
24020 "Glen Falls, NY"
24140 "Goldsboro, NC "
24340 "Grand Rapids-Wyoming, MI"
24540 "Greeley, CO"
24580 "Green Bay, WI "
24660 "Greensboro-High Point, NC"
24780 "Greenville, NC"
24860 "Greenville-Anderson-Mauldin, SC"
25180 "Hagerstown-Martinsburg, MD-WV"
25260 "Hanford-Corcoran, CA"
25420 "Harrisburg-Carlisle, PA"
25540 "Hartford-West Hartford-East Hartford, CT"
25860 "Hickory-Morganton-Lenoir, NC"
25940 "Hilton Head Island-Bluffton-Beaufort, SC"
26420 "Houston-Baytown-Sugar Land, TX"
26580 "Huntington-Ashland, WV-KY-OH"
26620 "Huntsville, AL"
26820 "Idaho Falls, ID"
26900 "Indianapolis, IN"
26980 "Iowa City, IA "
27100 "Jackson, MI"
27140 "Jackson, MS"
27260 "Jacksonville, FL"
27340 "Jacksonville, NC"
27500 "Janesville-Beloit, WI"
27740 "Johnson City, TN"
27780 "Johnstown, PA"
27980 "Kahului-Wailuku-Lahaina, HI"
28020 "Kalamazoo-Portage, MI"
28140 "Kansas City, MO-KS"
28420 "Kennewick-Richland, WA"
28660 "Killeen-Temple-Fort Hood, TX"
28700 "Kingsport-Bristol, TN-VA "
28940 "Knoxville, TN  \n29180   Lafayette, LA"
29200 "Lafayette-West Lafayette, IN"
29340 "Lake Charles, LA  "
29460 "Lakeland-Winter Haven, FL"
29540 "Lancaster, PA"
29620 "Lansing-East Lansing, MI"
29700 "Laredo, TX"
29740 "Las Cruces, NM"
29820 "Las Vegas-Paradise, NV"
30340 "Lewiston-Auburn, ME"
30460 "Lexington-Fayette, KY"
30780 "Little Rock-North Little Rock, AR "
30980 "Longview, TX "
31080 "Los Angeles-Long Beach-Anaheim, CA "
31140 "Louisville, KY-IN "
31180 "Lubbock, TX "
31420 "Macon, GA "
31540 "Madison, WI "
31700 "Manchester-Nashua, NH"
32580 "McAllen-Edinburg-Mission, TX"
32780 "Medford, OR"
32820 "Memphis, TN-MS-AR "
33100 "Miami-Fort Lauderdale-West Palm Beach, FL"
33340 "Milwaukee-Waukesha-West Allis, WI"
33460 "Minneapolis-St Paul-Bloomington, MN-WI "
33660 "Mobile, AL"
33700 "Modesto, CA"
33740 "Monroe, LA"
33780 "Monroe, MI"
33860 "Montgomery, AL"
34060 "Morgantown, WV "
34580 "Mount Vernon-Anacortes, WA    "
34740 "Muskegon-Norton Shores, MI"
34820 "Myrtle Beach-Conway-North Myrtle Beach, SC-NC"
34940 "Naples-Immokalee-Marco Island, FL"
34980 "Nashville-Davidson-Murfreesboro, TN "
35300 "New Haven-Milford, CT"
35380 "New Orleans-Metairie, LA"
35620 "New York-Newark- Jersey City, NY-NJ-PA (White Plains central city recoded to balance of metropolitan)"
35660 "Niles-Benton Harbor, MI"
35840 "North Port-Sarasota-Bradenton, FL \n35980   Norwich-New London, CT"
36100 "Ocala, FL"
36220 "Odessa, TX"
36260 "Ogden-Clearfield, UT"
36420 "Oklahoma City, OK"
36540 "Omaha-Council Bluffs, NE-IA "
36740 "Orlando, FL"
36780 "Oshkosh-Neenah, WI"
37100 "Oxnard-Thousand Oaks-Ventura, CA"
37340 "Palm Bay-Melbourne-Titusville, FL"
37460 "Panama City, FL"
37860 "Pensacola-Ferry Pass-Brent, FL"
37900 "Peoria, IL"
37980 "Philadelphia-Camden-Wilmington, PA-NJ-DE"
38060 "Phoenix-Mesa-Scottsdale, AZ"
38220 "Pine Bluff, AR"
38300 "Pittsburgh, PA"
38860 "Portland-South Portland, ME"
38900 "Portland-Vancouver-Hillsboro, OR-WA "
38940 "Port St. Lucie-Fort Pierce, FL"
39140 "Prescott, AZ"
39300 "Providence-Warwick, RI-MA"
39340 "Provo-Orem, UT"
39540 "Racine, WI"
39580 "Raleigh, NC"
39740 "Reading, PA"
39820 "Redding, CA"
40060 "Richmond, VA"
40140 "Riverside-San Bernardino-Ontario, CA"
40220 "Roanoke, VA "
40380 "Rochester, NY"
40420 "Rockford, IL"
40900 "Sacramento--Arden-Arcade–Roseville, CA"
40980 "Saginaw, MI"
41100 "St. George, UT"
41180 "St. Louis, MO-IL "
41420 "Salem, OR"
41500 "Salinas, CA"
41540 "Salisbury, MD"
41620 "Salt Lake City, UT "
41700 "San Antonio, TX"
41740 "San Diego-Carlsbad-San Marcos, CA"
41860 "San Francisco-Oakland-Fremont, CA"
41940 "San Jose-Sunnyvale-Santa Clara, CA"
42020 "San Luis Obispo-Paso Robles, CA"
42100 "Santa Cruz-Watsonville, CA"
42140 "Santa Fe, NM \n42200   Santa Maria-Santa Barbara, CA"
42220 "Santa Rosa-Petaluma, CA"
42340 "Savannah, GA"
42540 "Scranton--Wilkes-Barre, PA "
42660 "Seattle-Tacoma-Bellevue, WA"
43300 "Sherman-Dennison, TX"
43340 "Shreveport-Bossier City, LA"
43620 "Sioux Falls, SD"
43780 "South Bend-Mishawaka, IN-MI"
43900 "Spartanburg, SC"
44060 "Spokane-Spokane Valley, WA"
44100 "Springfield, IL"
44140 "Springfield, MA"
44180 "Springfield, MO"
44700 "Stockton-Lodi, CA"
45060 "Syracuse, NY"
45220 "Tallahassee, FL"
45300 "Tampa-St. Petersburg-Clearwater, FL"
45460 "Terre Haute, IN"
45780 "Toledo, OH "
45820 "Topeka, KS "
45940 "Trenton, NJ"
46060 "Tucson, AZ"
46140 "Tulsa, OK "
46340 "Tyler, TX"
46520 "Urban Honolulu, HI"
46540 "Utica-Rome, NY"
46700 "Vallejo-Fairfield, CA"
47220 "Vineland-Bridgeton, NJ"
47260 "Virginia Beach-Norfolk-Newport News, VA-NC "
47300 "Visalia-Porterville, CA"
47380 "Waco, TX"
47580 "Warner Robins, GA"
47900 "Washington-Arlington-Alexandria, DC-VA-MD-WV  "
47940 "Waterloo-Cedar Falls, IA "
48060 "Watertown-Fort Drum, NY"
48140 "Wausau, WI"
48620 "Wichita, KS"
48660 "Wichita Falls, TX"
48700 "Williamsport, PA"
49020 "Winchester, VA-WV"
49180 "Winston-Salem, NC"
49340 "Worcester, MA-CT"
49620 "York-Hanover, PA"
49660 "Youngstown-Warren-Boardman, OH-PA "
49740 "Yuma, AZ"
;

label values gtco     gtco;   
label define gtco    
	0           "NOT IDENTIFIED"                          
;
label values gtcbsast gtcbsast;
label define gtcbsast
	1           "PRINCIPAL CITY"                          
	2           "BALANCE"                                 
	3           "NONMETROPOLITAN"                         
	4           "NOT IDENTIFIED"                          
;
label values gtmetsta gtmetsta;
label define gtmetsta
	1           "METROPOLITAN"                            
	2           "NONMETROPOLITAN"                         
	3           "NOT IDENTIFIED"                          
;
label values gtindvpc gtindvpc;
label define gtindvpc
	0           "NOT IDENTIFIED, NONMETROPOLITAN,"        
;
label values gtcbsasz gtcbsasz;
label define gtcbsasz
	0           "NOT IDENTIFIED OR NONMETROPOLITAN"       
	2           "100,000 - 249,999"                       
	3           "250,000 - 499,999"                       
	4           "500,000 - 999,999"                       
	5           "1,000,000 - 2,499,999"                   
	6           "2,500,000 - 4,999,999"                   
	7           "5,000,000+"                              
;
label values gtcsa  gtcsa;  
label define gtcsa   
	0           "NOT IDENTIFIED OR NONMETROPOLITAN"
    104         "Albany-Schenectady, NY"
    106         "Albuquerque-Santa Fe-Las Vegas, NM"
	118         "Appleton-Oshkosh-Neenah, WI"     
    122         "Atlanta--Athens-Clarke County—Sandy Springs, GA"
    148         "Boston-Worcester-Providence, MA-RI-NH-CT"
    162         "Cape Coral-Fort Myers-Naples, FL"
    168         "Cedar Rapids-Iowa City, IA"
    170         "Charleston-Huntington-Ashland, WV-OH-KY"
    174         "Chattanooga-Cleveland-Dalton, TN-GA "
	184         "Cleveland-Akron-Elyria, OH (part)"
    194         "Columbus-Auburn-Opelika, GA-AL"
    206         "Dallas-Fort Worth, TX-OK"   
	216         "Denver-Aurora-Boulder, CO"               
	220         "Detroit-Warren-Flint, MI"  
    238         "El Paso-Las Cruses, TX-NM"        
	266         "Grand Rapids-Muskegon-Holland, MI (part)"
    268         "Greensboro--Winston-Salem--High Point, NC (part)" 
	273         "Greenville-Spartanburg-Anderson, SC"   
    276         "Harrisburg-York-Lebanon, PA"   
    278         "Hartford-West Hartford, CT"  
	304         "Johnson City-Kingsport-Bristol, TN-VA (part)"
    310         "Kalamazoo-Battle Creek-Portage, MI   "
    340         "Little Rock-North Little Rock, AR  " 
	348         "Los Angeles-Long Beach-Riverside, CA"    
	356         "Macon-Warner Robins-Fort Valley, GA (part)" 
    357         "Madison-Janesville-Beloit, WI   "
    370         "Miami-Fort Lauderdale-Port St. Lucie, FL "
	376         "Milwaukee-Racine-Waukesha, WI"           
    380         "Mobile-Daphne-Fairhope, AL" 
	408         "New York-Newark-Bridgeport, NY-NJ-CT-PA (part)"
    422         "Orlando-Deltona-Daytona Beach, FL"
	428         "Philadelphia-Reading-Camden, PA-NJ-DE-MD (part)"
    438         "Portland-Lewiston-South Portland, ME "
    440         "Portland-Vancouver-Salem, OR-WA"
	450         "Raleigh-Durham-Cary, NC (part)"          
	482         "Salt Lake City-Ogden-Clearfield, UT (part)"
    488         "San Jose-San Francisco-Oakland, CA"      
	500         "Seattle-Tacoma-Olympia, WA part" 
    515         "South Bend-Elkhart-Mishawaka, IN-MI  " 
    518         "Spokane-Spokane Valley-Coeur d’Alene, WA-ID   "
    546         "Visalia-Porterville-Hanford, CA   "
    548         "Washington-Baltimore-Northern Virginia, DC-MD-VA-WV (part)"  
;
* Since May 2012
label values penatvty penatvty;
label define penatvty
	57          "United States"                           
	60          "American Samoa"                          
	66          "Guam"                                    
	69          "Northern Marianas"                       
	73          "Puerto Rico"                             
	78          "U. S. Virgin Islands"                   
	100         "Albania"                                 
	102         "Austria"                                 
	103         "Belgium"                                 
	104         "Bulgaria"                                
	105         "Czechoslovakia"                          
	106         "Denmark"                                 
	108         "Finland"                                 
	109         "France"                                  
	110         "Germany"                                 
	116         "Greece"                                  
	117         "Hungary"                                 
	118         "Iceland"                                 
	119         "Ireland"                                 
	120         "Italy"                                   
	126         "Netherlands"                             
	127         "Norway"                                  
	128         "Poland"                                  
	129         "Portugal"                                
	130         "Azores"                                  
	132         "Romania"                                 
	134         "Spain"                                   
	136         "Sweden"                                  
	137         "Switzerland"                             
	138         "United Kingdom"                          
	139         "England"                                 
	140         "Scotland"                              
	142         "Northern Ireland"                        
	147         "Yugoslavia"                              
	148         "Czech Republic"                          
	149         "Slovakia"                                
	150         "Bosnia & Herzegovina"                    
	151         "Croatia"                                 
	152         "Macedonia"                               
	154         "Serbia"                                  
	155         "Estonia"                                 
	156         "Latvia"                                  
	157         "Lithuania"                               
	158         "Armenia"                                 
	159         "Azerbaijan"                              
	160         "Belarus"                                 
	161         "Georgia"                                 
	162         "Moldova"                                 
	163         "Russia"                                  
	164         "Ukraine"                                 
	165         "USSR"                                    
	166         "Europe, not specified"                 
	168         "Montenegro"                              
	200         "Afghanistan"                             
	202         "Bangladesh"                              
	203         "Bhutan"                                  
	205         "Myanmar (Burma)"                         
	206         "Cambodia"                                
	207         "China"                                   
	209         "Hong Kong"                               
	210         "India"                                   
	211         "Indonesia"                               
	212         "Iran"                                    
	213         "Iraq"                                    
	214         "Israel"                                  
	215         "Japan"                                   
	216         "Jordan"                                  
	217         "Korea"                                   
	218         "Kazakhstan"                              
	220         "South Korea"                             
	222         "Kuwait"                                  
	223         "Laos"                                    
	224         "Lebanon"                                 
	226         "Malaysia"                                
	228         "Mongolia"                                
	229         "Nepal"                                   
	231         "Pakistan"                                
	233         "Philippines"                             
	235         "Saudi Arabia"                            
	236         "Singapore"                               
	238         "Sri Lanka"                               
	239         "Syria"                                   
	240         "Taiwan"                                  
	242         "Thailand"                                
	243         "Turkey"                                  
	245         "United Arab Emirates"                    
	246         "Uzbekistan"                              
	247         "Vietnam"                                 
	248         "Yemen"                                   
	249         "Asia, not specified"                     
	300         "Bermuda"                                 
	301         "Canada"                                  
	303         "Mexico"                                  
	310         "Belize"                                  
	311         "Costa Rica"                              
	312         "El Salvador"                             
	313         "Guatemala"                               
	314         "Honduras"                                
	315         "Nicaragua"                               
	316         "Panama"                                  
	321         "Antigua and Barbuda"                     
	323         "Bahamas"                                 
	324         "Barbados"                                
	327         "Cuba"                                    
	328         "Dominica"                                
	329         "Dominican Republic"                      
	330         "Grenada"                                 
	332         "Haiti"                                   
	333         "Jamaica"                                 
	338         "St. Kitts--Nevis"                        
	339         "St. Lucia"                               
	340         "St. Vincent and the Grenadines"          
	341         "Trinidad and Tobago"                     
	343         "West Indies, not specified"              
	360         "Argentina"                               
	361         "Bolivia"                                 
	362         "Brazil"                                  
	363         "Chile"                                   
	364         "Columbia"                                
	365         "Ecuador"                                 
	368         "Guyana"                                  
	369         "Paraguay"                                
	370         "Peru"                                    
	372         "Uruguay"                                 
	373         "Venezuela"                               
	374         "South America, not specified"            
	399         "Americas, not specified"                 
	400         "Algeria"                                 
	407         "Cameroon"                                
	408         "Cape Verde"                              
	412         "Congo"                                   
	414         "Egypt"                                   
	416         "Ethiopia"                                
	417         "Eritrea"                                 
	421         "Ghana"                                   
	423         "Guinea"                                  
	425         "Ivory Coast"                             
	427         "Kenya"                                   
	429         "Liberia"                                 
	430         "Libya"                                   
	436         "Morocco"                                 
	440         "Nigeria"                                 
	444         "Senegal"                                 
	447         "Sierra Leone"                            
	448         "Somalia"                                 
	449         "South Africa"                            
	451         "Sudan"                                   
	453         "Tanzania"                                
	454         "Togo"                                    
	457         "Uganda"                                  
	459         "Zaire"                                   
	460         "Zambia"                                  
	461         "Zimbabwe"                                
	462         "Africa, not specified"                   
	501         "Australia"                               
	508         "Fiji"                                    
	511         "Marshall Islands"                        
	512         "Micronesia"                              
	515         "New Zealand"                             
	523         "Tonga"                                   
	527         "Samoa"                                   
	555         "Elsewhere"                               
;

*  Other Foreign Country Variables
label values pemntvty penatvty;                              

label values pefntvty penatvty;
   